/* ==========================================================================
   TETRO DATA ADAPTER & PRICE ENGINE
   Unified data store, live market rates & ticker engine
   ========================================================================== */

const EXCHANGES_DEF = [
  { id: 'nobitex', name: 'Nobitex', faName: 'نوبیتکس' },
  { id: 'wallex', name: 'Wallex', faName: 'والکس' },
  { id: 'ramzinex', name: 'Ramzinex', faName: 'رمزینکس' },
  { id: 'abantether', name: 'AbanTether', faName: 'آبان‌تتر' },
  { id: 'tetherland', name: 'TetherLand', faName: 'تترلند' },
  { id: 'tabdeal', name: 'Tabdeal', faName: 'تبدیل' },
  { id: 'exir', name: 'Exir', faName: 'اکسیر' },
  { id: 'bitpin', name: 'Bitpin', faName: 'بیت‌پین' }
];

// Cached formatters to eliminate repeated ICU/locale object allocations
const DATA_DATE_FORMATTERS = {
  time24: new Intl.DateTimeFormat('en-US', { hour12: false, hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Tehran' }),
  faMonthDay: new Intl.DateTimeFormat('fa-IR', { month: 'short', day: 'numeric', timeZone: 'Asia/Tehran' }),
  faYearMonth: new Intl.DateTimeFormat('fa-IR', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'Asia/Tehran' }),
  enMonthDay: new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', timeZone: 'Asia/Tehran' }),
  enYearMonth: new Intl.DateTimeFormat('en-US', { year: 'numeric', month: 'short', day: 'numeric', timeZone: 'Asia/Tehran' })
};

class DataAdapter {
  constructor() {
    const savedCurrency = (typeof localStorage !== 'undefined' && localStorage.getItem('tetro_currency')) || 'TOMAN';
    this.currentCurrency = savedCurrency === 'RIAL' ? 'RIAL' : 'TOMAN';
    this.rates = new Map();
    this.historyCache = new Map();
    this.subscribers = new Set();
    this.marketJsonTimer = null;
    this.basePrice = null;
  }

  init() {
    // Populate baseline structure (real data is loaded from market.json)
    EXCHANGES_DEF.forEach(ex => {
      this.rates.set(ex.id, {
        id: ex.id,
        name: ex.name,
        faName: ex.faName,
        status: 'live',
        lastSuccessAt: null,
        buyPrice: null,
        sellPrice: null,
        vol24h: 0,
        change24h: null,
        high24h: null,
        low24h: null,
        sparkline: [],
        lastUpdate: null,
        lastDirection: 'none'
      });
    });

    // Load real pre-built market.json (synced from real exchange APIs)
    this.loadMarketDataJson();

    // Check for updated market.json every 5 minutes (300s) in background
    this.marketJsonTimer = setInterval(() => {
      this.loadMarketDataJson();
    }, 300000);

    // Stop background polling when tab is hidden to save bandwidth and memory
    if (typeof document !== 'undefined') {
      document.addEventListener('visibilitychange', () => {
        if (document.hidden) {
          this.pauseAllPolling();
        } else {
          this.resumeAllPolling();
          this.loadMarketDataJson();
        }
      });
    }
  }

  pauseAllPolling() {
    if (this.marketJsonTimer) {
      clearInterval(this.marketJsonTimer);
      this.marketJsonTimer = null;
    }
  }

  resumeAllPolling() {
    if (!this.marketJsonTimer) {
      this.marketJsonTimer = setInterval(() => this.loadMarketDataJson(), 300000);
    }
  }

  // Load and apply market data snapshot generated by automated sync (GitHub Actions)
  async loadMarketDataJson() {
    try {
      const res = await fetch('./data/market.json', { cache: 'no-cache' });
      if (!res.ok) return;
      const data = await res.json();
      if (!data || !data.rates) return;

      if (data.timestamp || data.updatedAt) {
        this.lastMarketUpdate = data.timestamp ? new Date(data.timestamp * 1000) : new Date(data.updatedAt);
      }

      if (data.basePrice) {
        this.basePrice = data.basePrice;
      }

      // Update exchange rates directly from market snapshot
      const snapshotTime = data.timestamp ? (data.timestamp * 1000) : 0;
      Object.keys(data.rates).forEach(id => {
        const item = data.rates[id];
        const current = this.rates.get(id);
        if (current && item) {
          current.status = item.status || 'live';
          current.lastSuccessAt = item.lastSuccessAt || null;
          current.buyPrice = item.buyPrice != null ? item.buyPrice : current.buyPrice;
          current.sellPrice = item.sellPrice != null ? item.sellPrice : current.sellPrice;
          current.change24h = item.change24h != null ? Number(Number(item.change24h).toFixed(2)) : current.change24h;
          current.high24h = item.high24h != null ? item.high24h : current.high24h;
          current.low24h = item.low24h != null ? item.low24h : current.low24h;
          current.vol24h = item.vol24h != null ? item.vol24h : current.vol24h;
          current.lastUpdate = new Date(snapshotTime || Date.now());
          if (Array.isArray(item.sparkline) && item.sparkline.length > 0) {
            current.sparkline = item.sparkline;
          }
          this.rates.set(id, current);
        }
      });

      // Cache pre-fetched candles
      if (data.candles && typeof data.candles === 'object') {
        Object.keys(data.candles).forEach(tf => {
          const rawPoints = data.candles[tf];
          if (Array.isArray(rawPoints) && rawPoints.length > 0) {
            const cleanTf = tf.replace(/^[a-z0-9]+_/, '');
            const formatted = rawPoints.map(p => ({
              ...p,
              time: new Date(p.time),
              label: this.formatTimeLabel(new Date(p.time), cleanTf)
            }));
            this.historyCache.set(tf, formatted);
            if (tf.startsWith('aggregate_')) {
              this.historyCache.set(tf.replace('aggregate_', ''), formatted);
            } else if (!tf.includes('_')) {
              if (!this.historyCache.has(`aggregate_${tf}`)) {
                this.historyCache.set(`aggregate_${tf}`, formatted);
              }
              if (!data.candles[`wallex_${tf}`] && !this.historyCache.has(`wallex_${tf}`)) {
                this.historyCache.set(`wallex_${tf}`, formatted);
              }
            }
          }
        });
      }

      // Check candle freshness to identify halted exchanges (market closed 21:00 - 09:00)
      const nowMs = Date.now();
      const STALE_THRESHOLD_MS = 45 * 60 * 1000;
      this.rates.forEach((rate, id) => {
        const candles24 = this.historyCache.get(`${id}_24H`);
        if (candles24 && candles24.length > 0) {
          const lastCandle = candles24[candles24.length - 1];
          const candleTime = lastCandle.time instanceof Date ? lastCandle.time.getTime() : Number(lastCandle.time);
          if (nowMs - candleTime > STALE_THRESHOLD_MS) {
            rate.status = 'stale';
          }
        }
      });

      // Notify UI
      this.notify({
        type: 'market_loaded',
        stats: this.getAggregateStats()
      });

      if (window.chartEngine && window.chartEngine.loadData) {
        window.chartEngine.loadData();
      }
    } catch (err) {
      // Quietly ignore if market.json is not yet available
    }
  }

  // Subscribe to real-time price updates
  subscribe(callback) {
    this.subscribers.add(callback);
    return () => this.subscribers.delete(callback);
  }

  notify(event) {
    this.subscribers.forEach(cb => {
      try {
        cb(event);
      } catch (err) {
        console.error('Subscriber notification error:', err);
      }
    });
  }

  getExchangeRates() {
    return Array.from(this.rates.values());
  }

  getSparkline(exchangeId) {
    // 1. Try to get directly from cached 24H candles of that exchange
    const cKey = `${exchangeId}_24H`;
    if (this.historyCache.has(cKey)) {
      const cList = this.historyCache.get(cKey);
      if (Array.isArray(cList) && cList.length > 0) {
        return cList.map(p => Math.round(Number(p.close || p.price)));
      }
    }

    // 2. Fall back to pre-compiled sparkline array in rates map
    const rate = this.rates.get(exchangeId);
    if (rate && Array.isArray(rate.sparkline) && rate.sparkline.length > 0) {
      return rate.sparkline;
    }

    // 3. Fall back to market aggregate sparkline
    if (this.historyCache.has('aggregate_24H')) {
      const aggList = this.historyCache.get('aggregate_24H');
      if (Array.isArray(aggList) && aggList.length > 0) {
        return aggList.map(p => Math.round(Number(p.close || p.price)));
      }
    }

    return [];
  }

  getLastUpdateTime() {
    return this.lastMarketUpdate || new Date();
  }

  getAggregateStats() {
    const list = this.getExchangeRates().filter(r => r.status !== 'failed');
    if (!list.length) return null;

    // Filter valid prices in normal reasonable range
    const valid = list.filter(r => typeof r.buyPrice === 'number' && r.buyPrice > 50000 && r.buyPrice < 500000);
    if (!valid.length) return null;

    // Calculate median buy price for outlier rejection
    const sortedBuys = valid.map(r => r.buyPrice).sort((a, b) => a - b);
    const mid = Math.floor(sortedBuys.length / 2);
    const medianBuy = sortedBuys.length % 2 !== 0 ? sortedBuys[mid] : (sortedBuys[mid - 1] + sortedBuys[mid]) / 2;

    // Exclude any price with > 8% deviation from median
    const nonOutliers = valid.filter(r => Math.abs(r.buyPrice - medianBuy) / medianBuy <= 0.08);
    const pool = nonOutliers.length > 0 ? nonOutliers : valid;

    // Calculate Volume-Weighted Average Price (VWAP)
    let totalWeight = 0;
    let weightedBuy = 0;
    let weightedSell = 0;
    let weightedChange = 0;
    let totalVol = 0;
    let minLow = Infinity;
    let maxHigh = -Infinity;

    pool.forEach(item => {
      totalVol += (Number(item.vol24h) || 0);
      if (item.low24h != null && item.low24h < minLow) minLow = item.low24h;
      if (item.high24h != null && item.high24h > maxHigh) maxHigh = item.high24h;
    });

    const poolWithVol = pool.filter(item => (Number(item.vol24h) || 0) > 0);
    const vwapPool = poolWithVol.length > 0 ? poolWithVol : pool;

    vwapPool.forEach(item => {
      const vol = poolWithVol.length > 0 ? Number(item.vol24h) : 1;
      totalWeight += vol;
      weightedBuy += item.buyPrice * vol;
      weightedSell += (item.sellPrice || item.buyPrice) * vol;
      if (item.change24h != null) {
        weightedChange += Number(item.change24h) * vol;
      }
    });

    const avgBuy = totalWeight > 0 ? Math.round(weightedBuy / totalWeight) : Math.round(medianBuy);
    const avgSell = totalWeight > 0 ? Math.round(weightedSell / totalWeight) : avgBuy;
    const avgChange = totalWeight > 0 ? Number((weightedChange / totalWeight).toFixed(2)) : 0;

    return {
      avgBuy,
      avgSell,
      totalVolume: totalVol,
      high24h: maxHigh !== -Infinity ? maxHigh : avgBuy,
      low24h: minLow !== Infinity ? minLow : avgSell,
      change24h: avgChange
    };
  }

  formatPrice(rawToman, currency = this.currentCurrency) {
    if (rawToman == null) return '--';
    if (currency === 'RIAL') {
      return (rawToman * 10).toLocaleString('en-US') + ' ریال';
    }
    // Default TOMAN
    return rawToman.toLocaleString('en-US') + ' تومان';
  }

  formatPriceNum(rawToman, currency = this.currentCurrency) {
    if (rawToman == null) return '--';
    if (currency === 'RIAL') {
      return (rawToman * 10).toLocaleString('en-US');
    }
    return rawToman.toLocaleString('en-US');
  }

  setCurrency(curr) {
    this.currentCurrency = curr === 'RIAL' ? 'RIAL' : 'TOMAN';
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem('tetro_currency', this.currentCurrency);
    }
    this.notify({ type: 'currency_change', currency: this.currentCurrency });
  }

  async getHistory(timeframe = '24H', sourceId = 'aggregate') {
    const keys = sourceId === 'aggregate'
      ? [`aggregate_${timeframe}`, timeframe]
      : [`${sourceId}_${timeframe}`];

    for (const key of keys) {
      if (this.historyCache.has(key) && this.historyCache.get(key).length > 0) {
        return this.historyCache.get(key);
      }
    }

    const emptyDefault = [];
    emptyDefault.noData = true;
    emptyDefault.source = sourceId;
    emptyDefault.message = `داده‌های تاریخچه ${sourceId} در دسترس نیست`;
    return emptyDefault;
  }

  formatTimeLabel(date, timeframe) {
    if (timeframe === '1H' || timeframe === '24H') {
      return DATA_DATE_FORMATTERS.time24.format(date);
    }
    if (timeframe === '7D' || timeframe === '30D') {
      try {
        return DATA_DATE_FORMATTERS.faMonthDay.format(date);
      } catch (e) {
        return DATA_DATE_FORMATTERS.enMonthDay.format(date);
      }
    }
    // 1Y timeframe
    try {
      return DATA_DATE_FORMATTERS.faYearMonth.format(date);
    } catch (e) {
      return DATA_DATE_FORMATTERS.enYearMonth.format(date);
    }
  }
}

if (typeof window !== 'undefined') {
  window.dataAdapter = new DataAdapter();
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DataAdapter, EXCHANGES_DEF };
}
